### ISSUE TITLE
worker: no CPU limit specified for the container

### ISSUE THREAD

**Issue by nlbxyz** [TEAM-AAAAAAAAAAAAAAAA/bernstein#9]
![Screenshot_2022-10-21_18-29-18](https://user-images.githubusercontent.com/72011440/197244460-0f242e92-7c16-44a3-98ad-8f4c540d24d3.png)

**Comment by nlbxyz** [comment]
![Screenshot_2022-10-21_18-30-42](https://user-images.githubusercontent.com/72011440/197244701-e3bd605c-4c53-4a9e-9950-c644a7c55ea7.png)

Same for result deployment

**Comment by Cavonstavant** [comment]
yeah, but i actually don't care
